language: java

jdk:
    - oraclejdk8

branches:
    only:
        - master
          
before_script:
    - ./gradlew remote:midServerRMIRegistry &
    - ./gradlew remote:rmRMIRegistry &
    - sleep 15
    - ./gradlew rmi:rm:build rmi:rm:run -DrmName=car &
    - ./gradlew rmi:rm:build rmi:rm:run -DrmName=flight &
    - ./gradlew rmi:rm:build rmi:rm:run -DrmName=room &
    - sleep 15
    - ./gradlew rmi:mid-server:build rmi:mid-server:run &

script:
    - ./gradlew clean build test
